### ISSUE TITLE
activate appveyor hook for collective.zopeedit

### ISSUE THREAD

**Issue by gotcha** [collective/Collective#1012]
https://github.com/collective/collective.zopeedit

PS: I'd be happy to help maintaining the collective. In case you need help.

**Comment by gforcada** [comment]
@gotcha I had to register myself there and give them *shit* loads of permissions (hopefully not harmful), but it should be up and running.

I have no idea why it says gforcada on the URL while the repo is on collective: https://ci.appveyor.com/project/gforcada/collective-zopeedit

Let me know if that was what you wanted.

As for being an admin in collective org, I have no idea what's the policy, I'm 👍 on it though.

**Comment by gotcha** [comment]
Thanks Gil

**Comment by mauritsvanrees** [comment]
If Gil is +1 on adding Godefroid to the collective staff team, and I am +1 too, that seems enough to me. :-)
@gotcha, I have added you to the staff team. I haven't used appveyor, but I guess you should now have enough rights to do what you want.

**Comment by gotcha** [comment]
Thanks @mauritsvanrees

**Comment by gforcada** [comment]
I guess we can close...
