### ISSUE TITLE
Please add me to the collective

### ISSUE THREAD

**Issue by Pl4gue** [collective/Collective#1016]
Hey,
I would love to contribute to Collective projects / Plone add-ons. I master Python as well as JS and Java, and it would for me be great to be part of the collective organization!
Thank you!

**Comment by gforcada** [comment]
Hi @Pl4gue 

an invitation to join collective organization should be landing on your email inbox, re-open this ticket if not.

We are all looking forward to your contributions 😉 

Feel free to ask any question on our discussion forums: https://community.plone.org

Welcome to Plone!
