### ISSUE TITLE
Please add me to the collective

### ISSUE THREAD

**Issue by RDIL** [collective/Collective#1099]
Thank you

Woah that’s cool how does one make it auto fill like that owo

**Comment by gforcada** [comment]
Hi @RDIL 

an invitation to join collective organization should be landing on your email inbox, re-open this ticket if not.

We are all looking forward to your contributions 😉 

Feel free to ask any question on our discussion forums: https://community.plone.org

Welcome to Plone!

**Comment by RDIL** [comment]
K got it and joined.
