### ISSUE TITLE
Please add me to the collective

### ISSUE THREAD

**Issue by BaseMax** [collective/Collective#1125]
Offered by :
https://github.com/mpeeters

Thanks you,

Best Regards,
Max.

**Comment by gforcada** [comment]
Hi @BaseMax 

an invitation to join collective organization should be landing on your email inbox, re-open this ticket if not.

We are all looking forward to your contributions 😉 

Feel free to ask any question on our discussion forums: https://community.plone.org

Welcome to Plone!
