### ISSUE TITLE
Please add me to the collective

### ISSUE THREAD

**Issue by ironmaniiith** [collective/Collective#1129]
I'm Aalekh Jain, currently doing my GSOC under plone organization on the project plone-importexport. Kindly grant me the permissions collective.
Thank you

**Comment by gforcada** [comment]
Hi @ironmaniiith 

an invitation to join collective organization should be landing on your email inbox, re-open this ticket if not.

We are all looking forward to your contributions 😉 

Feel free to ask any question on our discussion forums: https://community.plone.org

Welcome to Plone!

**Comment by ironmaniiith** [comment]
Hi,
Thanks for adding me in
