### ISSUE TITLE
Enable Travis for https://github.com/collective/collective.eeafaceted.z3ctable

### ISSUE THREAD

**Issue by gbastien** [collective/Collective#1143]
Could you please enable Travis for https://github.com/collective/collective.eeafaceted.z3ctable ?
Thank you!
Gauthier
PS : it was enabled when the repository was in the IMIO organization a long time ago...

**Comment by jensens** [comment]
According to the settings it is enabled. 

![Screenshot at 2019-09-09 15-07-03](https://user-images.githubusercontent.com/157140/64533361-93dbb680-d313-11e9-99fe-d669f3e27e1d.png)

**Comment by jensens** [comment]
.... well, but not on TravisCI. I triggered a build. Looks fine so far

**Comment by gbastien** [comment]
@jensens thank you, we will have to fix it now ;-)
