### ISSUE TITLE
Please add me to the collective

### ISSUE THREAD

**Issue by UniversalSuperBox** [collective/Collective#1160]
I'd potentially like to use [iCalendar](https://github.com/collective/icalendar) for a project I'm working on, but it appears not to have any updates for a while, every PR is failing, and the documentation needs a rebuild.

I really hope I'm not stepping on toes here... Is there anyone I should get in contact with for maintainership of the project or documentation?

Thank you

**Comment by thet** [comment]
Hi, I used to maintain icalendar for a while. In the meantime others have taken over. But there was not much activity recently.
You're not stepping on anyone's toes, help would be highly appreciated!
I've sent you an invitation to the collective.

Just stick to submit pull requests. For releases ping me directly or ping someone else from the list of maintainers: https://pypi.org/project/icalendar/

We've somehow lost access to https://icalendar.readthedocs.io/en/latest/ . We should try to get it from @garbas or eventually host it on pythonhosted.

Happy hacking and welcome to the collective!

**Comment by UniversalSuperBox** [comment]
pythonhosted seems good, but how do you get your documentation there? Does it have to be part of your package? I'm having trouble finding documentation on it (ironically)

**Comment by thet** [comment]
Ah. thanks for checking!

**Comment by thet** [comment]
By the way, I've checked and looks like I have admin access to https://icalendar.readthedocs.io/en/latest/

**Comment by UniversalSuperBox** [comment]
I did some more digging through the issues, and it seems that https://github.com/collective/icalendar/pull/289 will fix the issue. If the build would have completed once in the past six months or so, we'd have proper CSS and JS. I suppose I can resolve the conflicts and merge, then.
