### ISSUE TITLE
Please add me to the collective

### ISSUE THREAD

**Issue by Ayush7614** [collective/Collective#1338]
* Name - Ayush Kumar

I am joining this community first of all i love to collobrate and contribute on github. I have also love met new people and help others i am doing web development android development and DSA I can take also part in various foss events and many winter of codes program i am top contributers in the kwoc and i am totally love with contribute on github so thats the reason i have to join this community and help peoples and looking forward to more contribute to the community

**Comment by Ayush7614** [comment]
Thanku

**Comment by mauritsvanrees** [comment]
I have sent you an invitation. Welcome!

You can follow the instructions in the automatic email, or visit https://github.com/collective to accept the invitation.

After accepting the invitation, your account is still private: others cannot see on your profile page that you are a member of the collective. That is fine.
But we are happy to have you as a public member. So if you would like to, please visit https://github.com/orgs/collective/people and make your account public there.
