### ISSUE TITLE
Please add me to the collective

### ISSUE THREAD

**Issue by RishabhDevbanshi** [collective/Collective#1363]
I would like to learn about the project and contribute to it. I have done Competitive Programming before and is currently 4 star on Codechef and also know some web development. I would be glad if I can add some value to this project. 
Thank You.

**Comment by mauritsvanrees** [comment]
I have sent you an invitation. Welcome!

You can follow the instructions in the automatic email, or visit https://github.com/collective to accept the invitation.

After accepting the invitation, your account is still private: others cannot see on your profile page that you are a member of the collective. That is fine.
But we are happy to have you as a public member. So if you would like to, please visit https://github.com/orgs/collective/people and make your account public there.
