### ISSUE TITLE
Please add me to the collective

### ISSUE THREAD

**Issue by aryashah2k** [collective/Collective#1367]
I am Arya, CS Sophomore and I would like to join this collective and explore the workflow and contribute to the same.
Thank you

**Comment by mauritsvanrees** [comment]
I have sent you an invitation. Welcome!

You can follow the instructions in the automatic email, or visit https://github.com/collective to accept the invitation.

After accepting the invitation, your account is still private: others cannot see on your profile page that you are a member of the collective. That is fine.
But we are happy to have you as a public member. So if you would like to, please visit https://github.com/orgs/collective/people and make your account public there.

**Comment by aryashah2k** [comment]
Thank You, I have successfully joined the organization and made my membership public!
