### ISSUE TITLE
 add me to the collective

### ISSUE THREAD

**Issue by Ayushparikh-code** [collective/Collective#1390]
Thank you

**Comment by mauritsvanrees** [comment]
I have sent you an invitation. Welcome!

You can follow the instructions in the automatic email, or visit https://github.com/collective to accept the invitation.

After accepting the invitation, your account is still private: others cannot see on your profile page that you are a member of the collective. That is fine.
But we are happy to have you as a public member. So if you would like to, please visit https://github.com/orgs/collective/people and make your account public there.

When I add new members, I always take a quick glance at their GitHub page. This random joke made me laugh, so thanks:

> The professor says "Welcome to English 101." The student panics. "What's wrong?" asks the professor. "I missed the first 4 English classes."
