### ISSUE TITLE
Adding new members to the collective

### ISSUE THREAD

**Issue by mauritsvanrees** [collective/Collective#1398]
Hi @collective/staff 

I seem to handle almost all requests for collective membership. I just approved about 15 or so, the oldest was about 2 weeks old. If others step up, newcomers don't have to wait this long. So a friendly reminder that anyone on staff can approve a new member and send an invitation. :-)

How I do it:

- View the issue.
- Copy the user id.
- Click on the user and open in a new tab. Take maybe ten seconds to look at their GitHub user page to see if anything is off. I have never seen anything that caused me to deny a request. You will see that most user pages are very much alike, very flashy, with lots of statistics and the same structure, so there must be some boilerplate. Anyway...
- In a new tab go to https://github.com/orgs/collective/people
- Click on 'Invite member', paste the user id, and select the user. In most cases just one user will pop up, but sometimes there are users with a similar id.
- You likely have to re-enter your password or a one-time 2factor auth code for the first invitation.
- Go back to the issue, add a comment that they have been been added, and close the issue.

I have the following text as a [saved reply](https://github.com/settings/replies):

-----------------
I have sent you an invitation. Welcome!

You can follow the instructions in the automatic email, or visit https://github.com/collective to accept the invitation.

After accepting the invitation, your account is still private: others cannot see on your profile page that you are a member of the collective. That is fine.
But we are happy to have you as a public member. So if you would like to, please visit https://github.com/orgs/collective/people and make your account public there.

-----------------

I will close this issue after creating it, as there is no action to take now. All requests have been handled.

**Comment by ale-rt** [comment]
I am glad to help if I can!
Unluckily if I go here https://github.com/orgs/collective/people I cannot see the "Invite member" link you are mentioning:
![image](https://user-images.githubusercontent.com/1300763/119949671-624cc800-bf9a-11eb-8327-47c819e4adac.png)
I am not sure if some permission need to be granted to my `ale-rt` account to make this possible or if I am looking in the wrong place.

**Comment by mauritsvanrees** [comment]
@ale-rt Aha, you are staff member, but that does not seem to grant any extra permissions. I gave you the role owner now. That should help.

**Comment by ale-rt** [comment]
It does! Thanks a lot!

**Comment by tkimnguyen** [comment]
@mauritsvanrees thank you for doing this, and @ale-rt for taking this on too! It's not great that this should fall on you. Let's figure out how to bubble this up so others can help too.

**Comment by tkimnguyen** [comment]
For example: could these requests get pushed on to the forum? or Slack/Discord?

**Comment by tkimnguyen** [comment]
I made @polyester an owner here. I admit I get so many notifications from GH that I do not see these, but I will look at tuning those better.

**Comment by mauritsvanrees** [comment]
Since we want to move more to Discord, if anyone wants to try out integration of GitHub with Discord, this issue list might be a nice project to start with. But such integration may make sense for *all* plone repositories, and that would immediately be overkill, making people ignore those messages, or the channel where they end up.

People should just look at their GitHub notifications regularly and feel responsible for a few of them. But I understand that notifications can be overwhelming, and that when you simply read them all, there is no time left to actionably do any action on them. There are probably lots of plone repositories where I don't get notifications for. I did that long ago, just to make it a bit more manageable. I am probably missing important stuff for those.

**Comment by tkimnguyen** [comment]
> People should just look at their GitHub notifications regularly and feel responsible for a few of them

Indeed... I am going to set aside time each week to do just that. I agree that just pushing all notifications to Discord just moves the problem to another platform.

**Comment by tkimnguyen** [comment]
I just did my first (in a long time)... https://github.com/collective/Collective/issues/1401

**Comment by tkimnguyen** [comment]
One note: I see you gave them write access, so that's what I just did for #1401

**Comment by mauritsvanrees** [comment]
I just make give them the Member role. I don't give any special permissions. But being Member should give them read and write access.

**Comment by tkimnguyen** [comment]
<img width="311" alt="image" src="https://user-images.githubusercontent.com/815418/120218870-f8cdf300-c1ff-11eb-8819-67660d5ac27e.png">
these are the choices

**Comment by mauritsvanrees** [comment]
Where do you see these choices?

Until now, during the invite I have simply given the role Member (choice is Member or Owner).

This is a recent one I added, and he has write access to all repositories:
https://github.com/orgs/collective/people/whyadiwhy

I just did another one. Screenshots:

![Screenshot 2021-06-02 at 17 14 46](https://user-images.githubusercontent.com/210587/120506516-485e1b80-c3c6-11eb-9981-e870fb2f0a56.png)

![Screenshot 2021-06-02 at 17 15 22](https://user-images.githubusercontent.com/210587/120506547-52801a00-c3c6-11eb-9d82-54d218ec542a.png)

**Comment by tkimnguyen** [comment]
wow that is really strange... not at all what I see !

**Comment by tkimnguyen** [comment]
I was sure I was following your steps above. On the next one I will see if I can capture URLs or screen shots

**Comment by nutjob4life** [comment]
I get what @mauritsvanrees gets, except in the  in "Dark dimmed" node.

1. Starting at https://github.com/orgs/collective/people I click <kbd>Invite member</kdb>
2. I type the username of a person to invite and click <kbd>Invite</kbd>

I then get the screen to choose role and team:

![Screen Shot 2021-06-04 at 3 35 29 PM](https://user-images.githubusercontent.com/814813/120860176-dbc05980-c54a-11eb-9cd6-3a313f0f18b8.png)

**Comment by tkimnguyen** [comment]
Yeah the other day I added someone else and saw what you both see. Very odd but we should be ok for now.
