### ISSUE TITLE
Add admin rights to repo

### ISSUE THREAD

**Issue by JeffersonBledsoe** [collective/Collective#1413]
As discussed in my [post about CI/ CD on the Plone Community Forum](https://community.plone.org/t/how-to-do-continuous-delivery-or-deployment-from-ci-for-collective-repositories/13448), I would like to make use of GitHub Action environments and secrets to attempt to ease PyPI deployment. In order to configure environments users are required to be admins for the repo.

Could I get admin privileges added for myself on the [collective/collective.contentrules.setfield](https://github.com/collective/collective.contentrules.setfield) repo so I could try this please? :)

**Comment by mauritsvanrees** [comment]
I gave you admin access now. Knock yourself out! :-)
