### ISSUE TITLE
[Hello!] Please add me to the collective

### ISSUE THREAD

**Issue by Rubix982** [collective/Collective#1436]
Hi, I'm Saif!

I'm a Open Source contributor. I love to work with teams, contributing to open source, recognizing business problems, evaluating requirements, learning from teammates and experiences.

I'm technically, practicing Open Source Software Development, DevOps, Cloud, Networking SWE, Full Stack Web Dev Engineering, Production Production & SRE, Database Administration, Technical Writing, and Linux.

Would love to be part of the Collective. Thank you and cheers!

**Comment by mauritsvanrees** [comment]
I have sent you an invitation. Welcome!

You can follow the instructions in the automatic email, or visit https://github.com/collective to accept the invitation.

After accepting the invitation, your account is still private: others cannot see on your profile page that you are a member of the collective. That is fine.
But we are happy to have you as a public member. So if you would like to, please visit https://github.com/orgs/collective/people and make your account public there.

**Comment by Rubix982** [comment]
Thank you, @mauritsvanrees.
