### ISSUE TITLE
Request to join collective

### ISSUE THREAD

**Issue by arky** [collective/Collective#1437]
Kindly requesting permission to collective for purpose of contributing to existing plone localization, collective add-on and hopeful releasing future add-ons.  Thanks

**Comment by ale-rt** [comment]
I have sent you an invitation. Welcome!

You can follow the instructions in the automatic email, or visit https://github.com/collective to accept the invitation.

After accepting the invitation, your account is still private: others cannot see on your profile page that you are a member of the collective. That is fine.
But we are happy to have you as a public member. So if you would like to, please visit https://github.com/orgs/collective/people and make your account public there.

**Comment by arky** [comment]
Thank you @ale-rt
