### ISSUE TITLE
Please add me to the collective

### ISSUE THREAD

**Issue by Tchoukoualeu** [collective/Collective#1449]
Thank you

I did receive the invitation last time, but it expired without me confirming it. Could you please send it again?

**Comment by mauritsvanrees** [comment]
No problem, let's try again. :-)
I have sent you an invitation. Welcome!

You can follow the instructions in the automatic email, or visit https://github.com/collective to accept the invitation.

After accepting the invitation, your account is still private: others cannot see on your profile page that you are a member of the collective. That is fine.
But we are happy to have you as a public member. So if you would like to, please visit https://github.com/orgs/collective/people and make your account public there.
