### ISSUE TITLE
Please add me to the collective

### ISSUE THREAD

**Issue by Jyoti-prakash-rout** [collective/Collective#1516]
I'm a Web Dev enthusiast & a junior pursuing my Bachelors in Computer Science & Engineering. I'm interested in Web Devlopment, Machine Learning & DevOps & I enjoy learning new things & stuff as well as I'm a Frontend Devloper with experience building Dynamic & Static Web pages. I am always interested in learning the answers to how, why, and what relates to the Technologies around me.

I would like to grow my programming skills by doing lots of Open Source contributions. Looking forward to learning, collaborating, and growing as a community.

**Comment by ale-rt** [comment]
I have sent you an invitation. Welcome!

You can follow the instructions in the automatic email, or visit https://github.com/collective to accept the invitation.

After accepting the invitation, your account is still private: others cannot see on your profile page that you are a member of the collective. That is fine.
But we are happy to have you as a public member. So if you would like to, please visit https://github.com/orgs/collective/people and make your account public there.
