### ISSUE TITLE
Please add me to the collective

### ISSUE THREAD

**Issue by github4maninder** [collective/Collective#1534]
I would like to be part of this organization and to contribute in any way

**Comment by github4maninder** [comment]
@mauritsvanrees , Hi Maurits  kindly assist me with this request.

**Comment by github4maninder** [comment]
thank you 👍🏻

**Comment by mauritsvanrees** [comment]
Ah, you have seen the invitation already. Welcome!

After accepting the invitation, your account is still private: others cannot see on your profile page that you are a member of the collective. That is fine.
But we are happy to have you as a public member. So if you would like to, please visit https://github.com/orgs/collective/people and make your account public there.

A question though, out of curiosity: the last year I have seen probably at least a hundred requests from GitHub users to be added to the Collective. Most are also a member of EddieCommunity (you too), and a lot also of Nvidia. Is there a list where those projects are mentioned?

**Comment by github4maninder** [comment]
yes, I would love to be a public member of collective organization. There is tons of resources, I am doing my best to understand most of it.
