### ISSUE TITLE
Please add me to the collective

### ISSUE THREAD

**Issue by ThomasKindermann** [collective/Collective#1543]
Im a dev in training from kitconcept

Thank you

**Comment by mauritsvanrees** [comment]
Someone already added you. Welcome!

After accepting the invitation on https://github.com/collective, your account is still private: others cannot see on your profile page that you are a member of the collective. That is fine.
But we are happy to have you as a public member. So if you would like to, please visit https://github.com/orgs/collective/people and make your account public there.
