### ISSUE TITLE
Please add me to the collective

### ISSUE THREAD

**Issue by Susmita-Dey** [collective/Collective#1547]
See my GitHub profile [here](https://www.github.com/Susmita-Dey)
I came to know from my friend's github profile.
I would like to join so that I can help the community, improve and learn in public.
Thank you

**Comment by ale-rt** [comment]
I have sent you an invitation. Welcome!

You can follow the instructions in the automatic email, or visit https://github.com/collective to accept the invitation.

After accepting the invitation, your account is still private: others cannot see on your profile page that you are a member of the collective. That is fine.
But we are happy to have you as a public member. So if you would like to, please visit https://github.com/orgs/collective/people and make your account public there.
