### ISSUE TITLE
Please add me to the collective

### ISSUE THREAD

**Issue by ksoe-codes** [collective/Collective#1636]
Thank you so much, this would be my first ever group and as i am very new to the industry i am still learning so please take me in, i hope i would be a great contributer

**Comment by ale-rt** [comment]
I have sent you an invitation. Welcome!

You can follow the instructions in the automatic email, or visit https://github.com/collective to accept the invitation.

After accepting the invitation, your account is still private: others cannot see on your profile page that you are a member of the collective. That is fine.
But we are happy to have you as a public member. So if you would like to, please visit https://github.com/orgs/collective/people and make your account public there.
