### ISSUE TITLE
Please add me to the collective

### ISSUE THREAD

**Issue by VipinChaudhary31** [collective/Collective#1657]
Hello,
I want to be part your organization.
I am really interested in your organization and your work.
I am a student but i want to gain some real life experience before completing my education as it will give me a edge.
I want to learn new tech with your help.
Please add me to your organization
Thank you

**Comment by ale-rt** [comment]
I have sent you an invitation. Welcome!

You can follow the instructions in the automatic email, or visit https://github.com/collective to accept the invitation.

After accepting the invitation, your account is still private: others cannot see on your profile page that you are a member of the collective. That is fine.
But we are happy to have you as a public member. So if you would like to, please visit https://github.com/orgs/collective/people and make your account public there.
