### ISSUE TITLE
Archive/delete ipdb fork?

### ISSUE THREAD

**Issue by gforcada** [collective/Collective#1745]
Hi @mauritsvanrees! 😄 👋🏾 

Looking at forks I noticed https://github.com/collective/ipdb that you did a commit at some point in __2011__.

Seems the [original repo](https://github.com/gotcha/ipdb) is still alive (it has python 3.11 support released already).

Should we archive/delete the fork you did? 🍀 

Happy new year! 🎉 🥳 

_yes, I'm in a new year clean up mode_ 🧹 😆

**Comment by mauritsvanrees** [comment]
I have archived the collective fork. Thanks!
