### ISSUE TITLE
Please Add Me to These Organisation

### ISSUE THREAD

**Issue by Sudhir878786** [collective/Collective#1750]
Hey My self Sudhir Sharma Currently pursuing my Btech Degree In computer science From @IITBhilai 
I am an open source enthusiastic  and interested in these organization
Kindly Add me to these organisation

Github @Sudhir878786

Linkedin https://www.linkedin.com/in/sudhir-sharma-4858ab21a/

**Comment by ale-rt** [comment]
I have sent you an invitation. Welcome!

You can follow the instructions in the automatic email, or visit https://github.com/collective to accept the invitation.

After accepting the invitation, your account is still private: others cannot see on your profile page that you are a member of the collective. That is fine.
But we are happy to have you as a public member. So if you would like to, please visit https://github.com/orgs/collective/people and make your account public there.
