### ISSUE TITLE
Please add me to the collective

### ISSUE THREAD

**Issue by rnicola-1605** [collective/Collective#1760]
I've been facing some issues while implementing plone protect within my Zope 5 application thats consists basically in persisting the IKeyManager Utility across multiple instances. Unfortunately, `plone.protect` and/or `plone.keyring` do not allow me to do so.
To get it working I developed a python script that serializes the Utility to make it persistent across all instances and even when the server restarts.

I took inspiration from the collective.beaker repository, and now would like to add it the organization.

Thank you!

**Comment by gforcada** [comment]
Hi @rnicola-1605 that sounds like a nice contribution! did you create a repository already for it, or are planning to patch the upstream packages? 🤔 

Note that `plone.protect` and `plone.keyring` are hosted in `plone` GitHub organization and not in `collective` GitHub organization, so getting access to the `collective` organization will still not allow you to push changes to them.

If you intend to create an add-on on its own, then yes, that's the route I would say 👍🏾 

Meanwhile you can create the repository on your own GitHub account and then we can transfer it to the `collective`
