### ISSUE TITLE
Please add me to the collective

### ISSUE THREAD

**Issue by supercomet329** [collective/Collective#1771]
# I checked

- [x] I understand that the Collective is dedicated to projects related to Plone.
- [x] I read https://collective.github.io/
- [x] I will follow the [Plone Code of Conduct](https://plone.org/foundation/about/materials/foundation-resolutions/code-of-conduct) - Be excellent to each other.

# Project/s I plan to work on:

1. ...
2. ...

# My motivation

...

Thank you!

**Comment by jensens** [comment]
May you tell us what do you plan to work on?

**Comment by supercomet329** [comment]
I would like to contribute this Collective Community.

**Comment by jensens** [comment]
And specific? You can fork a project and create a PR as usual, question is, why do you need more access?
