### ISSUE TITLE
Please add me to the collective

### ISSUE THREAD

**Issue by dev0715** [collective/Collective#1776]
Please consider, you do not need access to collective to create pull request or report an issue.

In order to not flood the collective with persons who actually do not need access, please tell us details.

# I checked

- [x] I understand that the Collective is dedicated to projects related to Plone.
- [x] I read https://collective.github.io/
- [x] I will follow the [Plone Code of Conduct](https://plone.org/foundation/about/materials/foundation-resolutions/code-of-conduct) - Be excellent to each other.

# Project/s I plan to work on:

1. Work with talent developers

Thank you!

**Comment by gforcada** [comment]
@dev0715 hi, thanks for reaching to the Plone Collective organization.

If you plan to work with talented developers you are at the right place 😉 but to actually work with them, you need to work on _something_, and that's the point of this issue/form here.

Note that you can collaborate _without_ being part of the `collective` organization:

- you can comment on existing issues/PRs
- you can create new issues
- you can create new PRs

Once a few of the above has been done, please re-open the ticket mentioning them 👍🏾 

If you tell us which areas are of your interest we can point you to some issues that might be interesting for you.
