### ISSUE TITLE
Please add me to the collective

### ISSUE THREAD

**Issue by Lil-Adonis** [collective/Collective#1782]
Please consider, you do not need access to collective to create pull request or report an issue.

In order to not flood the collective with persons who actually do not need access, please tell us details.

# I checked

- [x] I understand that the Collective is dedicated to projects related to Plone.
- [x] I read https://collective.github.io/
- [x] I will follow the [Plone Code of Conduct](https://plone.org/foundation/about/materials/foundation-resolutions/code-of-conduct) - Be excellent to each other.

# Project/s I plan to work on:

1.  Frontend related projects
2. little on backend

# My motivation
Just wanna be successful. came a few kilometer to quit

Thank you!

**Comment by gforcada** [comment]
Thanks for reaching to the Plone community, as state on the pre-filled description, we are looking forward to first acknowledge real interest, by creating issues, pull requests, commenting on existing ones, etc and then one can join the organization 👍🏾 

Not being part of the `collective` organization does not prevent one from contributing.

Use this issue to ask further questions if you have any. 🍀

**Comment by jensens** [comment]
Please add more detailed information why you need this access , like what do you plan to work on where classic forking and pull requests is not enough. Do reopen the issue after providing the information.
