### ISSUE TITLE
Please add me to the collective

### ISSUE THREAD

**Issue by nayanprasad** [collective/Collective#1785]
Please consider, you do not need access to collective to create pull request or report an issue.

In order to not flood the collective with persons who actually do not need access, please tell us details.

# I checked

- [x] I understand that the Collective is dedicated to projects related to Plone.
- [x] I read https://collective.github.io/
- [x] I will follow the [Plone Code of Conduct](https://plone.org/foundation/about/materials/foundation-resolutions/code-of-conduct) - Be excellent to each other.

# Project/s I plan to work on:

1. collective.elasticsearch
2. icalendar

# My motivation
To conquer the world through open source

Thank you!

**Comment by gforcada** [comment]
Hi @nayanprasad 👋🏾 

thanks for reaching out to Plone! 😄 we are glad that you reach to us to join the collective organization 🎉 

Unfortunately we had some problems with newcomers and now we would very much like to see some issues and pull requests being created before letting someone join the organization.

This way, you can already show that you are actually interested in it.

Please let us know if you need any guidance, as you already mention 2 specific repositories, I'm looking forward to review your issues and pull requests on them 😄
