### ISSUE TITLE
Please add me to the collective

### ISSUE THREAD

**Issue by justdaksh** [collective/Collective#1786]
Please consider, you do not need access to collective to create pull request or report an issue.

In order to not flood the collective with persons who actually do not need access, please tell us details.

# I checked

- [x] I understand that the Collective is dedicated to projects related to Plone.
- [x] I read https://collective.github.io/
- [x] I will follow the [Plone Code of Conduct](https://plone.org/foundation/about/materials/foundation-resolutions/code-of-conduct)
- [x] Be excellent to each other.

# Project I plan to work on:

1. Plone-Nuclia

Thank you!

**Comment by gforcada** [comment]
Hi @justdaksh thanks for taking the time to reach to us! 😄 

I see that you are interested in nuclia, but that has a different organization: https://github.com/nuclia

Where you trying to say that you want to contribute an addon for Plone that interacts with Nuclia? 🤔 

Then this is the place indeed 👍🏾 

You can use [`plonecli`](https://pypi.org/project/plonecli/) to create an addon, place it under your own account, and afterwards you can ask to transfer it here to the collective.

We have had some SPAM problems as of late, so we kindly ask new contributors to first create issues, pull requests, or brand new addons before we allow them to join the collective organization. I know it can be frustrating, but dealing with SPAM is as well 😓 

Have a nice day 🍀

**Comment by ebrehault** [comment]
Hi @gforcada!
@justdaksh is one of our GSoC students this year, he is mentored by @stevepiercy (and co-mentored by me) and he is working on providing AI searchability on docs.plone.org and training.plone.org contents.

So not a spammer :)

**Comment by gforcada** [comment]
@ebrehault oh, cool, that's probably something that could have been worth mentioning 😆 

@justdaksh check your inbox you should get an invitation ✉️ 🚀

**Comment by gforcada** [comment]
Invitation sent, please re-open if you don't see it or have any problem.

Welcome!! 🎉
