### ISSUE TITLE
Please add me to the collective

### ISSUE THREAD

**Issue by Sugamgoel28** [collective/Collective#1791]
Please consider, you do not need access to collective to create pull request or report an issue.

In order to not flood the collective with persons who actually do not need access, please tell us details.

# I checked

- [x] I understand that the Collective is dedicated to projects related to Plone.
- [x] I read https://collective.github.io/
- [x] I will follow the [Plone Code of Conduct](https://plone.org/foundation/about/materials/foundation-resolutions/code-of-conduct) - Be excellent to each other.

# Project/s I plan to work on:

1. Collaboration is key in software development, and I plan to work on a project that facilitates real-time collaboration among programmers. This project could involve building a web-based IDE (integrated development environment) with features like shared code editing, instant messaging, and version control integration. The aim is to make it easier for teams to work together, regardless of their physical location.

# My motivation
I am excited about the learning opportunities provided by your GitHub community. Access to a vast pool of resources, including libraries, frameworks, and documentation, will enable me to stay up to date with the latest industry developments and expand my technical proficiency. I believe that continuous learning is crucial in the rapidly evolving world of technology, and your community provides an ideal platform for growth.

Thank you!

**Comment by gforcada** [comment]
Hi @Sugamgoel28 your ideas are pretty cool! 👍🏾 

Unfortunately they are not much related to Plone, a python/react based CMS. Could it be that you are actually not that interested in Plone? 😅 

Please reopen if I indeed, you do have interest in Plone 😄

**Comment by Sugamgoel28** [comment]
Hi @gforcada, Thank you for your kind words and for considering my ideas. I sincerely thank you for reaching out and offering your assistance. If I have any other questions or topics in the future, I will definitely keep you in mind. Wishing you all the best and have a great day! 👋😊
