### ISSUE TITLE
Please add me to the collective

### ISSUE THREAD

**Issue by tedw87** [collective/Collective#1795]
Please consider, you do not need access to collective to create pull request or report an issue.

In order to not flood the collective with persons who actually do not need access, please tell us details.

# I checked

- [x] I understand that the Collective is dedicated to projects related to Plone.
- [x] I read https://collective.github.io/
- [x] I will follow the [Plone Code of Conduct](https://plone.org/foundation/about/materials/foundation-resolutions/code-of-conduct) - Be excellent to each other.

# Project/s I plan to work on:

1. collective.taxonomy
2. ...

# My motivation
I am making updates for the `volto-taxonomy` addon and I need to commit some changes also in the collective.taxonomy addon. 
...

Thank you!

**Comment by gforcada** [comment]
Hi @tedw87 👋🏾 

Note that to make contributions (thanks!!) to `collective.taxonomy`, or actually any other collective package, you don't need _to wait_, for this process to get approval. You still can create issues and pull requests meanwhile 😉

**Comment by alecghica** [comment]
@tedw87 is our colleague at Eau de Web.

**Comment by ale-rt** [comment]
I have sent you an invitation. Welcome!

You can follow the instructions in the automatic email, or visit https://github.com/collective to accept the invitation.

After accepting the invitation, your account is still private: others cannot see on your profile page that you are a member of the collective. That is fine.
But we are happy to have you as a public member. So if you would like to, please visit https://github.com/orgs/collective/people and make your account public there.
