### ISSUE TITLE
Please add me to the collective

### ISSUE THREAD

**Issue by hazigabriel** [collective/Collective#1803]
Hello,

I am Gabriel, a Front End Developer working for Eau De Web (Bucharest) and I'm looking forward to contribute towards Plone.

# I checked

- [X] I understand that the Collective is dedicated to projects related to Plone.
- [X] I read https://collective.github.io/
- [X] I will follow the [Plone Code of Conduct](https://plone.org/foundation/about/materials/foundation-resolutions/code-of-conduct) - Be excellent to each other.

# Project/s I plan to work on:

1. Volto

# My motivation
Joining your Plone Team would provide an ideal environment for me to further develop my skills and contribute to meaningful projects.

Thank you!

**Comment by jensens** [comment]
Invite is out.
