### ISSUE TITLE
Need help to configure the test conditions on collective.contentrules.mailtogroup

### ISSUE THREAD

**Issue by 1letter** [collective/Collective#1824]
I worked on Plone 6 configuration via plone/meta on this repro. My branch is ready, but i can't configure/delete the travis checks condition. They are not needed anymore, but i see a message in the tests overview "continuous-integration/travis-ci Expected — Waiting for status to be reported". How can i delete this condition?

Thats the PR:
https://github.com/collective/collective.contentrules.mailtogroup/pull/32

Can @collective/staff or an admin help?

**Comment by tkimnguyen** [comment]
You should ask in the forum if you don't get a response here

**Comment by fredvd** [comment]
@1letter there was one webhook configured for travis on the collective.contentrules.mailtogrup repo, I have removed it.

**Comment by fredvd** [comment]
Oh Can you please confirm if that was the problem and close this issue if so?

**Comment by 1letter** [comment]
@fredvd 
https://remarkablemark.org/blog/2021/03/15/github-remove-travis-ci/#organization

**Comment by davisagli** [comment]
@1letter I removed the required travis-ci status check. @fredvd This was in the branch protection settings (https://github.com/collective/collective.contentrules.mailtogroup/settings/branch_protection_rules/165288)

**Comment by 1letter** [comment]
Thank you! Great.

**Comment by fredvd** [comment]
@1letter thanks for the link to that document.  I didn’t see that David picked this up, I checked most items in that doc before, but I didn’t think at all about possible  branch protection rules.
