### ISSUE TITLE
Need help to configure variable settings on collective.contentrules.mailtogroup

### ISSUE THREAD

**Issue by 1letter** [collective/Collective#1825]
@collective/staff 
Is it possible to set Variables in a collective package? I can't do this as Member. In my own Repros i can set Variables.

I need two Variables:

TEST_OS_VERSIONS ["ubuntu-22.04", "ubuntu-20.04"]

TEST_PYTHON_VERSIONS ["3.8","3.9","3.10","3.11"]

**Comment by tkimnguyen** [comment]
Saw this but don't know the answer. It might be a good idea to ask in the forum.

**Comment by MrTango** [comment]
are you not using GitHub actions? There you normally set all the Python and Plone versions directly.

**Comment by MrTango** [comment]
I just checked the repo, it is not using GH actions, that should be changed.
Most repos here are using it already and we also have the Plone/Meta configuration which can be used by addons.

**Comment by 1letter** [comment]
> I just checked the repo, it is not using GH actions, that should be changed. Most repos here are using it already and we also have the Plone/Meta configuration which can be used by addons.

I have setup the GHA in this PR https://github.com/collective/collective.contentrules.mailtogroup/pull/32

**Comment by fredvd** [comment]
@1letter The variables (and secrets) you can set on the repository or environment level are only useful if you want to share them over many workflow files or share them on the organisation level.  To have a test matrix with python/plone versions you can define these in the workflow file themself, there's  no obligation to user repository variables/secrets. 

I hope this answers the question and I'll close the issue. If you have any other question or issues with the variables, please re-open.

**Comment by gforcada** [comment]
We should provide fallback values: https://github.com/plone/meta/issues/190
