### ISSUE TITLE
Member of github collective but not of pypi collective

### ISSUE THREAD

**Issue by cillianderoiste** [collective/Collective#1848]
I'm trying to publish an egg to https://pypi.org/project/collective.splitsitemap using zest.releaser. It fails with `the user 'goibhniu' isn't allowed to upload to project 'collective.splitsitemap'`. 
I've set up 2FA for pypi, and have configured a token in my .pypirc. I am a member of the collective org on github, but https://pypi.org/manage/organizations/ says I'm not a member of any organizations, so I wonder if I have been removed from the pypi collective organization, or perhaps I'm just doing something silly?

For reference, I'd like to publish this change, so we (Syslab) can use it for a project:
https://github.com/collective/collective.splitsitemap/pull/1

**Comment by gforcada** [comment]
GitHub organizations and pypi are unrelated, that's the problem :)

You need someone (I'm only on the Plone organization) to grant you access.

**Comment by cillianderoiste** [comment]
Thanks for explaining! I'll ask around :+1:
