### ISSUE TITLE
codecov secret settings in collective.z3cform.norobots

### ISSUE THREAD

**Issue by 1letter** [collective/Collective#1853]
i would like to enable a codecoverage via https://about.codecov.io/ in https://github.com/collective/collective.z3cform.norobots

i need access to the settings tab in the repro to set the `CODECOV_TOKEN` variable. Can anyone help me or set it?

Thanks!

**Comment by jensens** [comment]
I gave you the "maintain" role there. Please check if this works for your purpose.

**Comment by 1letter** [comment]
@jensens Thanks, but the maintainer role is not enough, I didn't see the navigation item "Security & Variables". Maybe an administrator in the project can create a token?

**Comment by jensens** [comment]
I can give you admin permissions for this repository if you enable 2FA.

**Comment by 1letter** [comment]
@jensens done, 2FA is enabled

**Comment by jensens** [comment]
@1letter Admin role granted for [collective.z3cform.norobots](https://github.com/collective/collective.z3cform.norobots) 
Do not drink and drive ;-)
