### ISSUE TITLE
How to archive a repo

### ISSUE THREAD

**Issue by do3cc** [collective/Collective#1870]
Hi,

I have been notified of a security alert for a repo I started 12 years ago. I am not using this code any more for a long time, it seems nobody else does. There are also no pypi releases for this.
I have no interest in updating dependencies for something I and seemingly nobody else uses. 
There might be people who may want to create such a functionality for themselves. It would be nice if they could use the repository name.
I am willing to follow some process to properly archive the repo. I can't do this right now. I suspect this was from an svn migration and because of that I don't have the necessary rights to archive it myself.
Anything you'd want me to write into the Readme?
Who can archive the repo? I suspect @jensens did the migration?

Repo in question:
https://github.com/collective/collective.colander

**Comment by jensens** [comment]
I archived it. Thanks for the information!
