### ISSUE TITLE
Please add me to the collective @abe-101

### ISSUE THREAD

**Issue by abe-101** [collective/Collective#1893]
Please consider, you do not need access to collective to create pull request or report an issue.

In order to not flood the collective with persons who actually do not need access, please tell us details.

# I checked

- [x] I understand that the Collective is dedicated to projects related to Plone.
- [x] I read https://collective.github.io/
- [x] I will follow the [Plone Code of Conduct](https://plone.org/foundation/about/materials/foundation-resolutions/code-of-conduct) - Be excellent to each other.

# Project/s I plan to work on:

1. [icalendar](https://github.com/collective/icalendar)

# My motivation

My project [MergeCal](https://github.com/mergecal/mergecal) uses icalendar and i would like to contribute back

Thank you!

**Comment by gforcada** [comment]
Hi @abe-101 , if you only plan to contribute on `icalendar`, would it be enough to give you access as a contributor there? or do you plan to expand your contributions to plone/volto repositories as well?

**Comment by abe-101** [comment]
Hi @gforcada 
Currently I have plans to contribute to iCalendar.
But I could see a future where I contribute to other Python projects - but I don't have immediate plans.
Its up to you 😃

**Comment by gforcada** [comment]
@abe-101 sorry, I was on holidays (I am still 🙃 ) but I found some time to add you to `icalendar`
