### ISSUE TITLE
Please add me to the collective

### ISSUE THREAD

**Issue by rioksane** [collective/Collective#1915]
# I checked

- [x] I understand that the Collective is dedicated to projects related to Plone.
- [x] I read https://collective.github.io/
- [x] I will follow the [Plone Code of Conduct](https://plone.org/foundation/about/materials/foundation-resolutions/code-of-conduct) - Be excellent to each other.

# Project/s I plan to work on:

1. https://github.com/collective/plone.app.locales

# My motivation
I want to help improve Finnish translations to Plone and any other Plone-related code I can help with. With collective access I could be assigned as a reviewer. 

Thank you!

**Comment by ale-rt** [comment]
I have sent you an invitation. Welcome!

You can follow the instructions in the automatic email, or visit https://github.com/collective to accept the invitation.

After accepting the invitation, your account is still private: others cannot see on your profile page that you are a member of the collective. That is fine.
But we are happy to have you as a public member. So if you would like to, please visit https://github.com/orgs/collective/people and make your account public there.
