### ISSUE TITLE
http://collective.github.com/ is broken

### ISSUE THREAD

**Issue by gbastien** [collective/Collective#953]
Hi,
instead of displaying the usual home page with explanation, it is redirected to https://collective.github.io/
This makes it difficult for new comers to find the link to join the collective.
Thank you and have a nice day,
Gauthier

**Comment by tkimnguyen** [comment]
I created https://collective.github.io to hold some slides... http://collective.github.com/ redirects there, yes. But if you want the "home page" of the collective, shouldn't you be using https://github.com/collective ?

**Comment by tkimnguyen** [comment]
Maybe I could add a link to https://github.com/collective... let me try that

**Comment by tkimnguyen** [comment]
I created https://collective.github.io (https://github.com/collective/collective.github.io ) but GitHub decided in its wisdom to redirect http://collective.github.com/ to https://collective.github.io

Maybe someone can figure out how to change https://github.com/collective/collective.github.com so it works again / does not redirect to https://collective.github.io? @jensens

**Comment by tkimnguyen** [comment]
I am not an owner of the collective org so I can't go to https://github.com/collective/collective.github.com/settings ... that might be where to control how the GitHub Pages are published

**Comment by jensens** [comment]
fixed
