### ISSUE TITLE
change description of collective.pdfdocument

### ISSUE THREAD

**Issue by petri** [collective/Collective#958]
Please change the github repository description text of [collective.pdfdocument](https://github.com/collective/collective.pdfdocument) from "PDF metadata extraction & cover page generation for collective.documentfile", into:

"PDF metadata extraction & cover page generation for collective.filemeta"

The collective.documentfile package was renamed to collective.filemeta a while back, hence the needed change.

**Comment by gforcada** [comment]
@petri is it ok like that? Re-open if not.
