### ISSUE TITLE
Readme Missing

### ISSUE THREAD

**Issue by prashant0598** [collective/Collective#992]
It will help people interested in this repository understand the project.

**Comment by jensens** [comment]
well, there is https://collective.github.io/

**Comment by prashant0598** [comment]
@jensens But the repository should also contain it. What are your views on it?

**Comment by jensens** [comment]
Just a README.rst with a link to that site? 

@prashant0598 pull requests are welcome!  TIA

**Comment by prashant0598** [comment]
@jensens  will do it definitely

**Comment by prashant0598** [comment]
@jensens have a look at #995
